title: jvernon.net
email: jonathansvernon@gmail.com
description: >-
  The internet home of Jonathan Vernon
baseurl: ""
url: "https://jvernon.net/"
twitter_username: modderwizard
github_username: modderwizard
